spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password: 
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create

logging:
  level:
    com.blog.api.exceptions: DEBUG

api:
  kakao:
    base-url: https://dapi.kakao.com/v2/search/blog
    auth-key: KakaoAK 6c2966d258c846c86b92773504c4136d
  naver:
    base-url: https://openapi.naver.com/v1/search/blog.json
    client-id: 193aAEonfwwuYc1BoYdq
    client-secret: Y9jCSvH1Wf

---

spring:
  config:
    activate:
      on-profile:
      - test-blog
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test-blog
    username: sa
    password: 

---

spring:
  config:
    activate:
      on-profile:
      - test-keyword
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test-keyword
    username: sa
    password: 
