spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/test
    username: sa
    password: 
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create

logging:
  level:
    com.blog.api.exceptions: DEBUG

api:
  kakao:
    base-url: https://dapi.kakao.com/v2/search/blog
    auth-key: KakaoAK 6c2966d258c846c86b92773504c4136d